version: '3.5'

volumes:
    production_postgres_data: {}
services:
    db:
        image: postgis/postgis
        env_file: conf/.env
        volumes:
            - production_postgres_data:/var/lib/postgresql/data
        expose:
            - 5432
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - .:/code
        ports:
            - 80:80
        env_file: conf/.env
        command: ['./docker/wait-for-db.sh', 'db', './manage.py', 'runserver', '0.0.0.0:80']
        depends_on:
            - db
